# Generated by Django 5.0.3 on 2024-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_you', models.CharField(max_length=100, verbose_name='Ваше імʼя')),
                ('name', models.CharField(max_length=100, verbose_name='Назва обʼяви')),
                ('pud_text', models.TextField(max_length=10000, verbose_name='Введіть текст')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
